
#The exception message repository contains the following data attributes for exceptions. 
#Note:  THEY HAVE TO BE CONFIGURED IN THE SPECIFIC ORDER TO AVOID ABNORMAL BEHAVIOR

#logicalName  	This attribute categorizes the error into a hierarchical namespace. 
#				The logical name helps organize the errors for developers to easily locate 
#					them and to help avoid duplicate errors. Each logical name will 
#					correspond to exactly one code. This attribute serves as a key for 
#					all entries in the repository.

#message  		The textual error message for display, which can contain placeholders for data. 
#					This attribute is used for all entries in the repository.

#code 	 		This attribute will contain a unique number assigned to this error within a 
#					certain category.  This attribute is used only for exception and validation entries. 

#severity 	 	The severity of the exception. Values can be: INFO, DEBUG, WARN, ERROR, FATAL. 
#					If this attribute is blank, it will default to ERROR.  This attribute is used 
#					only for exception entries.
				
#resolution 	A text field that provides possible solutions to the error for technical support staff. 
#					This attribute is used only for exception and validation entries. 


error.application.exception = ES_An application exception has occurred, 101, ERROR, ES_Please try again later
error.application.null = ES_A null pointer exception has occurred,102,ERROR, ES_Please try after some time
error.test.exception=throwing an exception from <b>{0}</b>, 100,ERROR, This is for testing

error.database.sqlexception.update = "Update for {0} failed",200,ERROR,"Try to save the data again"
error.database.sqlexception.remove = "Delete for {0} failed",201,ERROR,"Try to save the data again"
error.database.jpa.sqlexception.update = "Update for {0} failed",200,ERROR,"Try to save the data again"
error.database.sqlexception.cannotacquirelock.update = "Acquiring lock for update failed",200,ERROR,"Try to save data again"
error.database.sqlexception.cannotserialize.update = "Update conflicts",200,ERROR,"Try to save data again"
error.database.sqlexception.deadlockloser.update = "Transaction rolled back, DB error",200,ERROR,"Try to save data again"
error.database.sqlexception.transientexception.update = "Error while saving previously failed actions",200,ERROR,"Try to save again"

error.provider.creditcardvalidation.unavailable = "ES_Credit Card Validation could not be performed. Checkout process currently unavailable. Please try again later"error.provider.creditcardvalidation.unavailable = "Credit Card Validation could not be performed. Checkout process currently unavailable. Please try again later"
